const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    rotate: {
      '-180': '-180deg',
      '-90': '-90deg',
      '-45': '-45deg',
      '-25': '-25deg',
      0: '0',
      25: '25deg',
      45: '45deg',
      90: '90deg',
      135: '135deg',
      180: '180deg',
      270: '270deg',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      consilio: {
        100: '#d3faeb',
        200: '#8cf5d0',
        300: '#00f1b4',
        400: '#00ed91',
        500: '#00e35f',
        600: '#00cf55',
        700: '#00b54a',
        800: '#00983c',
        900: '#00772d',
      },
      gray: colors.trueGray,
      red: colors.red,
      blue: colors.lightBlue,
      yellow: colors.amber,
      rose: colors.rose,
      pink: colors.pink,
      fuchsia: colors.fuchsia,
      purple: colors.purple,
      violet: colors.violet,
      indigo: colors.indigo,
      lightBlue: colors.lightBlue,
      cyan: colors.cyan,
      teal: colors.teal,
      emerald: colors.emerald,
      green: colors.green,
      lime: colors.lime,
      amber: colors.amber,
      orange: colors.orange,
      warmGray: colors.warmGray,
      trueGray: colors.trueGray,
      coolGray: colors.coolGray,
      blueGray: colors.blueGray,
    },
  },
  purge: {
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
      'content/**/*.md',
    ],
  },
}
